version: '3.4'

services:
  webui:
    image: ${DOCKER_REGISTRY-}webui
    build:
      context: .
      dockerfile: src/WebUI/Dockerfile
    # depends_on:
    #   - db
    restart: on-failure
  
  clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
      context: src/WebUI/ClientApp
      dockerfile: Dockerfile
    depends_on:
      - webui
    restart: on-failure

  # db:
  #   image: "mcr.microsoft.com/mssql/server"
  #   environment:
  #     - "SA_PASSWORD=Your_password123"
  #     - "ACCEPT_EULA=Y"